// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int n = Integer.parseInt(args[0]);
		int count1 = 0;
		int count2 = 0; 
		for (int i = 0; i<n ;i++ ){
			double r1 = Math.random();
			if (r1>0.5) 
				count1 = count1+1;
		    else count2 = count2+1;
		}
    
    System.out.println("> 0.5:  " + count1 + " times");
	System.out.println("<= 0.5: " + count2 + " times");

		if (count2>0){System.out.println("Ratio:  " + (double)count1/count2);}

	}
}
